/* ============================================================
   CLARISÉ — Référentiel des 133 mécanismes (données)
   ------------------------------------------------------------
   CE FICHIER NE CONTIENT QUE DES DONNÉES. Aucune logique.
   C'est ici qu'on modifie un mécanisme : sa définition, ses critères,
   son statut. server.js construit les prompts à partir de ce fichier,
   il n'y a donc RIEN à changer dans server.js quand on édite un
   mécanisme — c'est tout l'intérêt de la séparation.

   Champs de chaque mécanisme :
     mot      : nom affiché (identique au glossaire de l'application)
     cat      : famille (voir FAMILLES ci-dessous)
     analyse  : statut pour l'ANALYSE d'un message isolé
                "OUI"     -> carte possible dès qu'un indice réel est là
                "PRUDENT" -> exige un indice net, mais carte FERME si retenu
                "HIST"    -> seulement si l'historique du journal le montre
                "NON"     -> jamais une carte d'analyse (Coach/glossaire only)
     crit     : ✓ ce qu'il faut réellement observer pour le retenir
     pas      : ✗ ce qui y ressemble mais ne suffit PAS (anti-faux positif)
     question : question discriminante à poser côté Coach en cas de doute
     verif    : ce qui manque pour trancher (usage interne du Coach)

   Statuts fournis par le référentiel, avec trois arbitrages produit qui
   priment volontairement dessus :
     - Harcèlement          -> OUI  (gardé analysable)
     - Illusion de contrôle -> OUI  (gardé analysable)
     - Pression sexuelle    -> NON  (exclu de l'analyse : le message seul
                                     ne permet pas d'en juger sans risque)
   ============================================================ */

const FAMILLES = [
  "Pression émotionnelle et affective",
  "Contrôle de la relation et de l'environnement",
  "Manipulation du discours et du raisonnement",
  "Altération de la réalité et de la responsabilité",
  "Dévalorisation et atteinte à l'identité",
  "Pouvoir, domination et emprise",
  "Techniques d'influence et d'engagement",
  "Mécanismes d'attachement et de maintien dans la relation",
  "Effets psychologiques et cognitifs",
  "Biais cognitifs favorisant la prise ou le maintien",
];

const MECANISMES = [

  // ---- Pression émotionnelle et affective ----
  { mot: "Abus de confiance", cat: "Pression émotionnelle et affective", analyse: "HIST",
    crit: "La confiance initiale est explicitement invoquée ou décrite, puis une information, faveur, intimité ou ressource obtenue grâce à cette confiance est utilisée au détriment de la personne.",
    pas: "Une promesse de confidentialité ou une relation de confiance, sans preuve d’exploitation ultérieure, ne suffit pas.",
    question: "Qu’est-ce qui avait été promis ou compris au départ, et qu’est-ce qui a été fait ensuite grâce à la confiance que tu avais accordée ?",
    verif: "Chronologie confiance → accès obtenu → usage contraire à l’accord ; nature de l’accord initial ; bénéfice tiré de la rupture." },
  { mot: "Cadeau empoisonné", cat: "Pression émotionnelle et affective", analyse: "HIST",
    crit: "Le geste présenté comme généreux crée concrètement une charge, une obligation ou une difficulté prévisible pour le destinataire, puis cette charge est utilisée ou laissée à sa charge.",
    pas: "Un cadeau simplement mal choisi, encombrant ou décevant n’est pas nécessairement un cadeau empoisonné.",
    question: "Est-ce que cette personne savait que ce cadeau allait te mettre en difficulté, et s’en est-elle ensuite servie pour obtenir quelque chose ou te faire culpabiliser ?",
    verif: "Contexte du cadeau ; connaissance préalable des contraintes ; conséquences ; éventuelle demande ou culpabilisation ensuite." },
  { mot: "Chantage affectif", cat: "Pression émotionnelle et affective", analyse: "OUI",
    crit: "L’affection, la relation, l’approbation ou la proximité sont conditionnées à l’obéissance : aimer/rester/parler seulement si l’autre fait ce qui est demandé.",
    pas: "Exprimer une limite réelle sur ce qu’on peut accepter dans une relation n’est pas automatiquement du chantage affectif.",
    question: "Si tu refuses cette demande, est-ce que la personne retire réellement son affection ou menace la relation pour te faire céder ?",
    verif: "Ce qui est conditionné ; possibilité réelle de dire non ; proportion entre le comportement demandé et la menace de retrait du lien." },
  { mot: "Climat de terreur", cat: "Pression émotionnelle et affective", analyse: "HIST",
    crit: "La peur vient d’une imprévisibilité répétée des colères, sanctions ou explosions, au point que la personne adapte son comportement avant même qu’une demande soit formulée.",
    pas: "Une dispute forte ou une personne de mauvaise humeur une fois ne suffit pas à établir un climat de terreur.",
    question: "Est-ce que tu changes régulièrement ce que tu fais pour éviter une réaction que tu ne peux pas prévoir ?",
    verif: "Fréquence des explosions ; imprévisibilité ; comportements d’évitement de la cible ; peur des conséquences." },
  { mot: "Culpabilisation", cat: "Pression émotionnelle et affective", analyse: "OUI",
    crit: "Le message attribue à l’autre la responsabilité d’une émotion, d’un choix ou d’un problème afin qu’il se sente obligé de réparer, s’excuser ou céder.",
    pas: "Dire « je suis triste que tu ne viennes pas » exprime une émotion ; cela devient culpabilisant si la tristesse est transformée en faute ou dette.",
    question: "Le message te laisse-t-il la possibilité de dire non, ou te présente-t-il comme responsable de son mal-être si tu refuses ?",
    verif: "Responsabilité imputée ; lien avec la demande ; présence d’un devoir moral implicite ; espace laissé au refus." },
  { mot: "Flatterie intéressée", cat: "Pression émotionnelle et affective", analyse: "OUI",
    crit: "Le compliment est directement couplé à une demande ou à une faveur, et exploite le désir de rester conforme à l’image positive donnée.",
    pas: "Un compliment sincère suivi plus tard d’une demande n’est pas suffisant.",
    question: "Est-ce que le compliment disparaît ou se retourne contre toi lorsque tu refuses ce qui est demandé ?",
    verif: "Proximité temporelle compliment-demande ; caractère ciblé du compliment ; pression si refus ; répétition." },
  { mot: "Future faking", cat: "Pression émotionnelle et affective", analyse: "PRUDENT",
    crit: "Des promesses d’avenir importantes servent à maintenir la relation ou différer une décision, et un historique montre qu’elles sont répétées sans réalisation concrète.",
    pas: "Une promesse non tenue, un projet repoussé ou un changement de plan ne permet pas d’inférer une intention de tromper.",
    question: "Est-ce la première fois que cette promesse est faite, ou y a-t-il déjà eu plusieurs promesses similaires sans changement concret ?",
    verif: "Promesses antérieures ; actes concrets ; délais ; répétition après menace de rupture ou conflit." },
  { mot: "Honte", cat: "Pression émotionnelle et affective", analyse: "OUI",
    crit: "Le message attaque la valeur morale, la dignité, le corps ou la respectabilité de la personne pour provoquer un sentiment d’indignité.",
    pas: "Exprimer un désaccord moral précis avec un acte n’est pas nécessairement faire honte à la personne entière.",
    question: "Le reproche porte-t-il sur un comportement précis, ou te fait-il sentir que c’est toi, en tant que personne, qui serais indigne ou honteuse ?",
    verif: "Cible de l’attaque : acte ou identité ; exposition à autrui ; lien avec une demande ou une soumission attendue." },
  { mot: "Love bombing", cat: "Pression émotionnelle et affective", analyse: "HIST",
    crit: "Une intensité affective très rapide et disproportionnée au stade de la relation est suivie de demandes d’engagement, d’exclusivité, de fusion ou, plus tard, de contrôle/dévalorisation.",
    pas: "Une relation passionnelle ou démonstrative n’est pas en soi du love bombing.",
    question: "Cette intensité s’accompagnait-elle de demandes pour aller très vite, t’isoler, t’engager ou renoncer à des limites ?",
    verif: "Durée de la relation ; rythme des déclarations ; cadeaux/contacts ; demandes d’exclusivité ; évolution ultérieure." },
  { mot: "Menace", cat: "Pression émotionnelle et affective", analyse: "OUI",
    crit: "Une conséquence négative est annoncée ou suggérée pour provoquer la peur et obtenir une action, un silence ou un renoncement.",
    pas: "Annoncer une conséquence factuelle ou légitime n’est pas forcément une menace.",
    question: "La conséquence annoncée décrit-elle simplement ce qui arrivera, ou est-elle utilisée pour te faire peur afin que tu obéisses ?",
    verif: "Nature de la conséquence ; contrôle de l’auteur sur celle-ci ; intention coercitive observable ; gravité et crédibilité." },
  { mot: "Prophétie", cat: "Pression émotionnelle et affective", analyse: "OUI",
    crit: "L’auteur prédit avec assurance l’échec, l’abandon, la solitude ou l’incapacité de l’autre de façon à décourager une décision autonome.",
    pas: "Exprimer une inquiétude réaliste sur un risque futur n’est pas une prédiction dévalorisante.",
    question: "Cette prédiction s’appuie-t-elle sur des faits précis, ou sert-elle surtout à te convaincre que tu ne peux pas réussir sans cette personne ?",
    verif: "Certitude affichée ; fondement factuel ; attaque de la capacité ; lien avec une décision que l’autre veut empêcher." },
  { mot: "Réciprocité contrainte", cat: "Pression émotionnelle et affective", analyse: "OUI",
    crit: "Une faveur, un sacrifice ou un cadeau passé est explicitement transformé en dette pour rendre une demande actuelle difficile à refuser.",
    pas: "Proposer un échange ou rappeler une réciprocité négociée n’est pas automatiquement coercitif.",
    question: "Si tu refuses, est-ce que la faveur passée est utilisée pour te présenter comme ingrat·e, égoïste ou déloyal·e ?",
    verif: "Faveur passée ; contrepartie exigée ; disproportion ; possibilité de refuser sans accusation d’ingratitude." },
  { mot: "Victimisation", cat: "Pression émotionnelle et affective", analyse: "PRUDENT",
    crit: "Une mise en cause est détournée vers la souffrance de l’auteur de façon à neutraliser la responsabilité et recentrer l’attention sur lui.",
    pas: "Parler de sa propre souffrance n’est pas se victimiser ; elle peut être réelle et pertinente.",
    question: "Quand tu soulèves un problème, est-ce que ton sujet est traité avant que la conversation bascule sur ce que l’autre dit subir de ta part ?",
    verif: "Sujet initial ; réponse donnée ; reconnaissance ou non du tort ; déplacement de l’attention ; répétition." },
  { mot: "Vol de la joie", cat: "Pression émotionnelle et affective", analyse: "HIST",
    crit: "Les moments de réussite, détente ou joie sont de façon répétée suivis d’une critique, crise ou information utilisée pour casser le moment.",
    pas: "Une mauvaise nouvelle qui tombe au mauvais moment ou une remarque maladroite ne suffit pas.",
    question: "Est-ce que ce type de critique ou de crise apparaît régulièrement précisément quand tu vas bien, réussis quelque chose ou te détends ?",
    verif: "Plusieurs épisodes ; timing ; caractère évitable ; réaction de l’auteur à la joie ; conséquence sur la capacité à se réjouir." },

  // ---- Contrôle de la relation et de l'environnement ----
  { mot: "Campagne de diffamation", cat: "Contrôle de la relation et de l'environnement", analyse: "PRUDENT",
    crit: "Des affirmations dévalorisantes sont diffusées à des tiers de manière répétée, avec un effet d’isolement, de décrédibilisation ou de préparation d’un conflit/procédure.",
    pas: "Une personne racontant sa version d’un conflit ou demandant du soutien à des proches n’est pas automatiquement une campagne de diffamation.",
    question: "Sais-tu ce qui a réellement été dit aux autres, à combien de personnes, et si des éléments faux ou privés ont été répétés ?",
    verif: "Nombre de tiers ; contenu diffusé ; vérifiabilité ; répétition ; conséquences sociales ou institutionnelles." },
  { mot: "Comparaison rabaissante", cat: "Contrôle de la relation et de l'environnement", analyse: "OUI",
    crit: "La personne est comparée à un tiers de façon défavorable pour diminuer sa valeur ou la pousser à se conformer.",
    pas: "Une comparaison descriptive ou utile n’est pas forcément rabaissante.",
    question: "La comparaison sert-elle à donner une information utile, ou surtout à te faire sentir inférieur·e pour que tu changes ?",
    verif: "Objet de la comparaison ; tonalité ; demande implicite ; répétition ; possibilité de discuter sans humiliation." },
  { mot: "Contrôle de l'information", cat: "Contrôle de la relation et de l'environnement", analyse: "PRUDENT",
    crit: "Des informations importantes pour décider ou agir sont retenues, filtrées ou monopolisées de manière répétée, ce qui crée une dépendance décisionnelle.",
    pas: "Oublier de transmettre une information ou vouloir garder une information privée n’est pas forcément du contrôle.",
    question: "Quelles informations te sont refusées, et en quoi cela t’empêche-t-il concrètement de décider ou d’agir pour toi-même ?",
    verif: "Nature des informations ; droit/nécessité d’accès ; fréquence ; avantage tiré du contrôle ; conséquences concrètes." },
  { mot: "Contrôle économique", cat: "Contrôle de la relation et de l'environnement", analyse: "OUI",
    crit: "L’accès de la personne à son argent, ses comptes, moyens de paiement ou ressources est limité, surveillé ou conditionné par l’autre.",
    pas: "Un budget commun convenu, une transparence financière réciproque ou une mesure temporaire acceptée n’est pas en soi du contrôle économique.",
    question: "Peux-tu accéder librement à ton argent et prendre des décisions raisonnables sans devoir obtenir son autorisation ?",
    verif: "Propriété des fonds ; consentement ; symétrie ; liberté d’accès ; conséquences en cas de refus." },
  { mot: "Double visage", cat: "Contrôle de la relation et de l'environnement", analyse: "HIST",
    crit: "Un contraste stable apparaît entre une image publique charmante et des comportements privés hostiles, avec éventuellement usage de cette réputation pour décrédibiliser la cible.",
    pas: "Être plus sociable en public qu’en privé est banal et ne suffit pas.",
    question: "Peux-tu donner deux ou trois exemples où la même situation est traitée très différemment selon qu’il y a des témoins ou non ?",
    verif: "Exemples publics/privés comparables ; répétition ; réaction des témoins ; utilisation de la bonne réputation." },
  { mot: "Escalade graduelle des exigences", cat: "Contrôle de la relation et de l'environnement", analyse: "HIST",
    crit: "Les demandes ou restrictions augmentent par petites étapes, chaque nouveau niveau s’appuyant sur le précédent.",
    pas: "Des responsabilités qui évoluent naturellement avec une relation ou un projet ne constituent pas nécessairement une escalade manipulatoire.",
    question: "Qu’est-ce qui était demandé au début, et qu’est-ce qui est exigé aujourd’hui que tu n’aurais probablement pas accepté d’emblée ?",
    verif: "Chronologie des demandes ; première limite ; augmentation ; possibilité de refus ; conséquences." },
  { mot: "Ferrage", cat: "Contrôle de la relation et de l'environnement", analyse: "HIST",
    crit: "Le contrôle s’intensifie spécifiquement après qu’un engagement affectif, matériel ou institutionnel a rendu la sortie plus coûteuse.",
    pas: "Une relation devient naturellement plus interdépendante après un engagement ; cela ne prouve pas un « ferrage ».",
    question: "Qu’est-ce qui a changé dans ses exigences juste après que tu sois devenu·e plus engagé·e ou moins libre de partir ?",
    verif: "Moment de l’engagement ; changement avant/après ; nature des nouvelles restrictions ; réaction au refus." },
  { mot: "Flagrant délit", cat: "Contrôle de la relation et de l'environnement", analyse: "HIST",
    crit: "Une provocation ou pression précède la réaction de la cible, puis cette réaction est isolée du contexte et utilisée comme preuve contre elle.",
    pas: "Une personne peut réagir légitimement à une colère ou documenter un incident sans l’avoir provoqué.",
    question: "Que s’est-il passé dans les minutes ou heures avant la réaction qui a ensuite été utilisée contre toi ?",
    verif: "Séquence avant la réaction ; provocations ; demandes d’arrêt ; enregistrement ; usage ultérieur de la réaction." },
  { mot: "Gatekeeping relationnel", cat: "Contrôle de la relation et de l'environnement", analyse: "OUI",
    crit: "L’auteur impose qui la personne peut voir, quand, où ou sous quelles conditions, même sans interdiction totale.",
    pas: "Organiser des disponibilités ou poser une limite liée à la sécurité n’est pas automatiquement du gatekeeping.",
    question: "Peux-tu choisir librement qui tu vois et dans quelles conditions, ou faut-il régulièrement obtenir son accord ?",
    verif: "Règles imposées ; réciprocité ; justification ; sanctions ; possibilité de négocier." },
  { mot: "Harcèlement", cat: "Contrôle de la relation et de l'environnement", analyse: "OUI",
    crit: "Il existe une répétition objectivable de messages, appels, demandes ou contacts malgré absence de réponse, demande d’arrêt ou limite claire.",
    pas: "Plusieurs messages dans une conversation active ne suffisent pas à qualifier un harcèlement.",
    question: "Après que tu as demandé d’arrêter ou cessé de répondre, combien de fois et par quels moyens la personne a-t-elle continué à te contacter ?",
    verif: "Nombre/fréquence ; durée ; demandes d’arrêt ; canaux utilisés ; motif d’urgence éventuel." },
  { mot: "Hoovering", cat: "Contrôle de la relation et de l'environnement", analyse: "PRUDENT",
    crit: "Après une séparation ou prise de distance, les tentatives de retour sont répétées, insistantes et combinent excuses, promesses, cadeaux, crises ou pressions malgré une limite.",
    pas: "Demander une fois à reparler après une rupture n’est pas du hoovering.",
    question: "As-tu clairement demandé de la distance ou du non-contact, et comment la personne réagit-elle à cette limite ?",
    verif: "Statut de la séparation ; limite exprimée ; fréquence ; moyens de contact ; promesses antérieures." },
  { mot: "Instrumentalisation d'un tiers", cat: "Contrôle de la relation et de l'environnement", analyse: "OUI",
    crit: "Un enfant, proche, collègue ou institution est utilisé comme relais d’une demande, pression, menace ou accusation que l’auteur pourrait normalement adresser directement.",
    pas: "Passer une information par un tiers pour des raisons pratiques n’est pas toujours une instrumentalisation.",
    question: "Pourquoi ce message passe-t-il par ce tiers plutôt que directement, et ce tiers est-il mis en position de porter le conflit ?",
    verif: "Rôle du tiers ; capacité de contact direct ; contenu transmis ; consentement du tiers ; effet recherché." },
  { mot: "Intermittence (chaud-froid)", cat: "Contrôle de la relation et de l'environnement", analyse: "HIST",
    crit: "Un historique montre une alternance imprévisible de chaleur et de froideur/attaque sans lien clair avec les événements, qui entretient l’attente du retour des bons moments.",
    pas: "Les variations normales d’humeur et de disponibilité ne suffisent pas.",
    question: "Quand la personne redevient très chaleureuse après une période dure, y a-t-il un déclencheur clair ou cela arrive-t-il de façon imprévisible ?",
    verif: "Chronologie ; intensité ; déclencheurs ; prévisibilité ; effet sur l’attente et l’attachement." },
  { mot: "Isolement", cat: "Contrôle de la relation et de l'environnement", analyse: "OUI",
    crit: "Le message dénigre l’entourage, pose un choix « eux ou moi », multiplie les obstacles aux contacts ou présente les proches comme dangereux/inutiles afin de réduire les liens extérieurs.",
    pas: "Exprimer une inquiétude fondée sur une relation réellement nocive n’est pas automatiquement de l’isolement.",
    question: "La personne critique-t-elle un proche précis pour un fait précis, ou plusieurs de tes relations au point que ton cercle s’est réduit ?",
    verif: "Nombre de relations concernées ; justification ; liberté de contact ; sanctions ; évolution du réseau." },
  { mot: "Privation / perturbation volontaire du sommeil", cat: "Contrôle de la relation et de l'environnement", analyse: "HIST",
    crit: "Des discussions, appels, réveils ou exigences sont volontairement répétés aux heures de sommeil malgré demandes de repos, avec un effet d’épuisement.",
    pas: "Une crise exceptionnelle ou un bébé qui réveille la nuit n’est pas une privation volontaire du sommeil.",
    question: "Quand tu demandes de reporter la discussion pour dormir, est-ce que cette demande est respectée ou la pression continue-t-elle ?",
    verif: "Horaires ; fréquence ; demandes de report ; motifs ; possibilité de dormir ; conséquence sur les décisions." },
  { mot: "Punition imprévisible", cat: "Contrôle de la relation et de l'environnement", analyse: "HIST",
    crit: "Un même comportement est accepté puis sanctionné sans changement explicite de règle, de façon répétée, obligeant la cible à deviner ce qui déclenchera la prochaine réaction.",
    pas: "Changer d’avis ou ajuster une règle avec explication n’est pas une punition imprévisible.",
    question: "Pour une même situation, peux-tu prévoir la règle ou la réaction, ou est-ce qu’elle change sans explication d’un jour à l’autre ?",
    verif: "Comportements identiques ; réactions divergentes ; règles annoncées ; sanctions ; fréquence." },
  { mot: "Semer la zizanie", cat: "Contrôle de la relation et de l'environnement", analyse: "PRUDENT",
    crit: "Des propos attribués à des tiers, consignes incompatibles ou informations partielles créent des conflits entre personnes qui n’ont pas vérifié directement entre elles.",
    pas: "Rapporter un désaccord réel entre deux personnes n’est pas forcément semer la zizanie.",
    question: "As-tu pu vérifier directement avec la personne concernée ce qu’elle aurait réellement dit ou demandé ?",
    verif: "Propos exacts ; vérification auprès du tiers ; divergences ; répétition ; bénéfice relationnel." },
  { mot: "Silence punitif", cat: "Contrôle de la relation et de l'environnement", analyse: "PRUDENT",
    crit: "Le retrait de communication survient après un désaccord et fonctionne comme une sanction ou un moyen d’obtenir excuses, soumission ou reprise de contact.",
    pas: "Prendre de la distance pour se calmer est sain si la pause est annoncée, proportionnée et suivie d’une reprise.",
    question: "La personne dit-elle qu’elle a besoin d’une pause et revient-elle ensuite, ou le silence dure-t-il jusqu’à ce que tu cèdes ou t’excuses ?",
    verif: "Durée ; annonce de la pause ; reprise prévue ; motif ; ce qui fait cesser le silence." },
  { mot: "Stonewalling", cat: "Contrôle de la relation et de l'environnement", analyse: "PRUDENT",
    crit: "La personne ferme systématiquement toute possibilité de traiter un sujet : refus, départ, non-réponse ou changement de sujet, sans reprise ultérieure.",
    pas: "Une pause ponctuelle pour éviter l’escalade n’est pas du stonewalling.",
    question: "Après avoir interrompu la discussion, la personne accepte-t-elle de reprendre le sujet plus tard dans des conditions plus calmes ?",
    verif: "Sujets concernés ; demandes de reprise ; délai ; fréquence ; capacité de résolution." },
  { mot: "Surveillance / monitoring", cat: "Contrôle de la relation et de l'environnement", analyse: "OUI",
    crit: "Des demandes ou actes visent à suivre de façon régulière localisation, messages, fréquentations, horaires ou activités, au-delà d’un accord librement consenti.",
    pas: "Partager volontairement sa localisation ou se prévenir mutuellement pour des raisons pratiques n’est pas automatiquement de la surveillance.",
    question: "Peux-tu désactiver ou refuser cette surveillance sans reproche, pression, sanction ou accusation ?",
    verif: "Consentement ; réciprocité ; fréquence ; accès technique ; conséquences d’un refus." },
  { mot: "Test de limites", cat: "Contrôle de la relation et de l'environnement", analyse: "HIST",
    crit: "Une limite clairement exprimée est franchie à plusieurs reprises, souvent par petites étapes, et l’auteur observe ou exploite l’absence de conséquence.",
    pas: "Une incompréhension ponctuelle ou une limite ambiguë ne suffit pas.",
    question: "Après que tu as formulé clairement la limite, qu’est-ce qui s’est passé les fois suivantes ?",
    verif: "Limite formulée ; compréhension ; répétition ; progression ; réaction quand elle est rappelée." },
  { mot: "Triangulation", cat: "Contrôle de la relation et de l'environnement", analyse: "OUI",
    crit: "Un tiers est invoqué ou comparé pour créer rivalité, jalousie, insécurité ou pour donner artificiellement plus de poids au point de vue de l’auteur.",
    pas: "Mentionner l’avis pertinent d’un tiers ou demander une médiation n’est pas automatiquement trianguler.",
    question: "Le tiers apporte-t-il une information pertinente, ou sert-il surtout à te comparer, te mettre en compétition ou renforcer la pression ?",
    verif: "Rôle du tiers ; pertinence ; vérifiabilité ; effet de rivalité ; contact direct possible." },

  // ---- Manipulation du discours et du raisonnement ----
  { mot: "Ambiguïté / flou", cat: "Manipulation du discours et du raisonnement", analyse: "OUI",
    crit: "Le message reste suffisamment vague pour permettre plusieurs interprétations et offre ensuite à l’auteur la possibilité de nier, déplacer ou redéfinir ce qu’il avait demandé.",
    pas: "Une formulation imprécise par maladresse ou manque d’information n’est pas nécessairement manipulatoire.",
    question: "Quand tu demandes une formulation précise ou un accord clair, la personne répond-elle clairement ou maintient-elle volontairement plusieurs versions possibles ?",
    verif: "Point qui devrait être précis ; possibilité de clarification ; réactions aux demandes de précision ; réinterprétations ultérieures." },
  { mot: "Caricature", cat: "Manipulation du discours et du raisonnement", analyse: "OUI",
    crit: "Le message transforme la position réelle de l’autre en version extrême, absurde ou offensante, puis répond à cette version plutôt qu’à ce qui a été dit.",
    pas: "Résumer maladroitement ou interpréter différemment n’est pas forcément caricaturer.",
    question: "Si tu remets côte à côte ce que tu as réellement dit et ce qu’on te fait dire, qu’est-ce qui a été ajouté ou exagéré ?",
    verif: "Propos initial exact ; reformulation ; éléments ajoutés ; correction acceptée ou non." },
  { mot: "Double contrainte", cat: "Manipulation du discours et du raisonnement", analyse: "OUI",
    crit: "Deux consignes simultanées se contredisent et rendent toute réponse fautive ou insatisfaisante.",
    pas: "Deux demandes exigeantes ne sont pas automatiquement paradoxales si elles peuvent être articulées.",
    question: "Si tu choisis l’une des deux consignes, est-ce que l’autre est ensuite utilisée pour te reprocher ton choix ?",
    verif: "Formulation exacte des consignes ; compatibilité pratique ; sanctions associées." },
  { mot: "Déplacement des poteaux / Moving the goalposts", cat: "Manipulation du discours et du raisonnement", analyse: "HIST",
    crit: "Après qu’un critère demandé est atteint, un nouveau critère apparaît et empêche de considérer le problème comme résolu, de façon répétée.",
    pas: "Modifier une attente parce que de nouvelles informations apparaissent n’est pas forcément déplacer les poteaux.",
    question: "Quel était le critère annoncé au départ, et qu’est-ce qui a été demandé de plus une fois ce critère atteint ?",
    verif: "Critère initial ; preuve qu’il a été rempli ; nouveau critère ; justification ; répétition." },
  { mot: "Fausse question / question orientée", cat: "Manipulation du discours et du raisonnement", analyse: "OUI",
    crit: "La formulation contient déjà la réponse attendue, un jugement ou une accusation, de sorte qu’une réponse libre devient difficile.",
    pas: "Une question rhétorique ou une question suggérant une préférence n’est pas toujours coercitive.",
    question: "Peux-tu répondre honnêtement « non » à cette question sans être immédiatement accusé·e ou disqualifié·e ?",
    verif: "Présupposé intégré ; coût du désaccord ; existence d’options réelles ; tonalité." },
  { mot: "Fausse équivalence", cat: "Manipulation du discours et du raisonnement", analyse: "OUI",
    crit: "Deux actes de nature, gravité ou contexte très différents sont présentés comme équivalents pour minimiser le plus grave ou neutraliser une responsabilité.",
    pas: "Comparer deux comportements pour rechercher une règle commune n’est pas toujours fallacieux.",
    question: "Les deux faits comparés ont-ils réellement une gravité et des conséquences comparables, ou la comparaison réduit-elle artificiellement le plus grave ?",
    verif: "Nature des actes ; conséquences ; intention ; fréquence ; asymétrie de gravité." },
  { mot: "Généralisation", cat: "Manipulation du discours et du raisonnement", analyse: "OUI",
    crit: "Un événement ponctuel est transformé en caractéristique générale à l’aide de formulations absolues ou d’une attribution durable.",
    pas: "Employer « toujours » ou « jamais » dans le langage courant ne suffit pas à prouver une manipulation.",
    question: "Quand tu apportes un contre-exemple, la personne peut-elle nuancer, ou maintient-elle l’étiquette générale quoi qu’il arrive ?",
    verif: "Fréquence réelle ; possibilité de citer des exceptions ; rôle de l’absolu dans le reproche ; répétition." },
    { mot: "Nuage d'encre", cat: "Manipulation du discours et du raisonnement", analyse: "PRUDENT",
    crit: "Face à une question précise, la réponse multiplie digressions, jargon, détails secondaires ou contre-sujets sans traiter le point central.",
    pas: "Une réponse longue ou complexe n’est pas automatiquement un nuage d’encre.",
    question: "Après la réponse, peux-tu identifier clairement ce qui répond à ta question initiale, ou celle-ci reste-t-elle toujours sans réponse ?",
    verif: "Question initiale ; réponse ; présence d’une réponse explicite ; répétition ; effet d’épuisement." },
  { mot: "Ordre flou", cat: "Manipulation du discours et du raisonnement", analyse: "OUI",
    crit: "Une consigne est suffisamment vague pour laisser l’autre deviner l’action attendue, puis le résultat est critiqué comme s’il avait été évident.",
    pas: "Une demande simplement imprécise ne suffit pas si la personne accepte de préciser.",
    question: "Quand tu demandes ce qui est attendu concrètement, obtiens-tu une réponse précise avant d’être jugé·e sur le résultat ?",
    verif: "Consigne exacte ; demande de précision ; réponse ; reproche final ; répétition." },
  { mot: "Passif-agressif", cat: "Manipulation du discours et du raisonnement", analyse: "OUI",
    crit: "L’hostilité ou le reproche est exprimé indirectement par sous-entendus, ironie, retrait ou formulations qui nient explicitement l’hostilité.",
    pas: "Un ton sec, une plaisanterie ou une difficulté à exprimer ses émotions ne suffit pas à qualifier un passif-agressif.",
    question: "Quand tu demandes directement s’il y a un problème, la personne peut-elle le nommer, ou continue-t-elle à nier tout en te punissant indirectement ?",
    verif: "Contenu littéral ; sous-entendu ; possibilité de clarification ; répétition ; congruence entre parole et comportement." },
  { mot: "Plus c'est gros, plus ça passe", cat: "Manipulation du discours et du raisonnement", analyse: "PRUDENT",
    crit: "Une affirmation factuelle très catégorique est utilisée comme base d’une conclusion ou d’une pression alors que le message ne fournit aucune preuve et que sa véracité est incertaine.",
    pas: "Être très sûr de soi ne signifie pas mentir, et l’IA ne peut pas déclarer une affirmation fausse sans vérification externe.",
    question: "Qu’est-ce qui permet de vérifier cette affirmation indépendamment de l’assurance avec laquelle elle est formulée ?",
    verif: "Source de l’affirmation ; éléments vérifiables ; contradictions documentées ; importance de l’affirmation pour la décision." },
  { mot: "Présupposé", cat: "Manipulation du discours et du raisonnement", analyse: "OUI",
    crit: "Une accusation ou un fait contestable est intégré grammaticalement comme déjà acquis, obligeant l’autre à se défendre avant même d’avoir pu contester la prémisse.",
    pas: "Toute phrase contenant une présupposition linguistique n’est pas manipulatoire ; c’est un mécanisme normal du langage.",
    question: "Quelle affirmation est présentée comme déjà vraie dans cette phrase alors qu’elle n’a pas été établie ?",
    verif: "Prémisse implicite ; contestabilité ; lien avec accusation/demande ; possibilité de la remettre en question." },
  { mot: "Pétition de principe", cat: "Manipulation du discours et du raisonnement", analyse: "PRUDENT",
    crit: "Des valeurs ou principes élevés sont invoqués pour obtenir confiance, conformité ou patience, mais le récit fournit des comportements répétés qui les contredisent.",
    pas: "Déclarer une valeur ne prouve ni hypocrisie ni manipulation.",
    question: "Quels comportements concrets contredisent ce principe, et est-ce que le principe est invoqué au moment où l’on te demande de faire confiance ou d’attendre ?",
    verif: "Principe déclaré ; comportements concrets ; répétition de l’écart ; usage du principe pour rassurer ou obtenir quelque chose." },
  { mot: "Recadrage", cat: "Manipulation du discours et du raisonnement", analyse: "OUI",
    crit: "Le sens d’un acte problématique est redéfini après coup pour en diminuer la portée ou déplacer la responsabilité, sans traiter l’effet concret ni le fait initial.",
    pas: "Donner un contexte ou préciser une intention n’est pas automatiquement un recadrage manipulateur.",
    question: "La nouvelle explication apporte-t-elle du contexte tout en reconnaissant le fait, ou sert-elle surtout à faire disparaître le problème ?",
    verif: "Fait initial ; nouvelle définition proposée ; reconnaissance ou non de l’impact ; changement de responsabilité." },
  { mot: "Reproche ambigu", cat: "Manipulation du discours et du raisonnement", analyse: "OUI",
    crit: "Un reproche fort est formulé sans préciser le comportement concerné, laissant l’autre chercher seul sa faute et proposer des réparations au hasard.",
    pas: "Une personne peut être momentanément incapable de formuler précisément ce qui la blesse.",
    question: "Quand tu demandes exactement ce qui t’est reproché, obtiens-tu un fait précis ou restes-tu obligé·e de deviner ?",
    verif: "Nature du reproche ; demandes de précision ; réponse ; conséquences si l’autre ne devine pas." },
  { mot: "Whataboutism", cat: "Manipulation du discours et du raisonnement", analyse: "PRUDENT",
    crit: "Au lieu de répondre au sujet soulevé, l’auteur introduit immédiatement une faute supposée de l’autre pour déplacer la conversation et éviter le point initial.",
    pas: "Signaler un autre problème réel n’est pas du whataboutism si le sujet initial est aussi traité ou si le contre-sujet est explicitement séparé.",
    question: "Est-ce que le problème que tu as soulevé reçoit une réponse avant que la conversation parte sur tes propres torts ?",
    verif: "Sujet initial ; présence d’une réponse ; moment du contre-grief ; possibilité de revenir au premier sujet." },

  // ---- Altération de la réalité et de la responsabilité ----
  { mot: "Confusion", cat: "Altération de la réalité et de la responsabilité", analyse: "OUI",
    crit: "Le message juxtapose contradictions, changements de version et causalités multiples de façon à rendre difficile l’identification d’une position stable ou d’un fait clair.",
    pas: "Se corriger, hésiter ou préciser un souvenir n’est pas nécessairement créer de la confusion.",
    question: "Quand tu demandes une version claire des faits, la réponse devient-elle plus cohérente ou ajoute-t-elle encore de nouvelles contradictions ?",
    verif: "Versions successives ; contradictions précises ; demandes de clarification ; possibilité d’obtenir une version stable." },
  { mot: "DARVO", cat: "Altération de la réalité et de la responsabilité", analyse: "PRUDENT",
    crit: "Après une mise en cause, on observe la séquence : nier le fait, attaquer la crédibilité ou le caractère de celui qui le soulève, puis se présenter comme la véritable victime.",
    pas: "Une défense ferme ou un contre-grief ne constitue pas à elle seule un DARVO.",
    question: "Peux-tu reconstituer ce qui a été soulevé d’abord, puis ce que l’autre a nié, attaqué et finalement présenté comme ce qu’il subissait lui-même ?",
    verif: "Mise en cause initiale ; négation ; attaque personnelle ; inversion victime/responsable ; ordre de la séquence." },
  { mot: "Gaslighting", cat: "Altération de la réalité et de la responsabilité", analyse: "PRUDENT",
    crit: "La perception, mémoire ou capacité de jugement de l’autre est de façon répétée invalidée, avec pour effet ou fonction de diminuer sa confiance dans sa propre réalité.",
    pas: "Un désaccord de mémoire, une erreur sincère ou dire « je ne me souviens pas comme toi » ne suffit pas.",
    question: "Est-ce un désaccord précis sur un souvenir, ou retrouves-tu régulièrement le même message selon lequel ta mémoire ou ta perception ne serait jamais fiable ?",
    verif: "Répétition ; nature des invalidations ; éléments objectifs disponibles ; impact sur la confiance en soi." },
  { mot: "Mensonge & déni", cat: "Altération de la réalité et de la responsabilité", analyse: "HIST",
    crit: "Un fait vérifiable est nié ou falsifié de façon répétée malgré des éléments concordants, et ce déni sert à empêcher toute responsabilité ou décision fondée sur le réel.",
    pas: "Une différence de souvenir ou une information incomplète ne permet pas de conclure à un mensonge.",
    question: "Quels éléments vérifiables permettent de distinguer une erreur de mémoire d’un déni de faits déjà établis ?",
    verif: "Preuves indépendantes ; versions successives ; possibilité d’erreur ; bénéfice tiré du déni." },
  { mot: "Minimisation", cat: "Altération de la réalité et de la responsabilité", analyse: "OUI",
    crit: "Un acte ou son impact est explicitement réduit : « ce n’est rien », « tu exagères », « juste une blague », de façon à invalider la gravité ou le ressenti sans traiter le fait.",
    pas: "Mettre un événement en perspective ou rassurer n’est pas toujours minimiser.",
    question: "La personne peut-elle reconnaître que l’acte a eu un impact même si elle le juge moins grave, ou nie-t-elle ton droit d’être affecté·e ?",
    verif: "Fait initial ; gravité objective possible ; reconnaissance de l’impact ; responsabilité ; répétition." },
  { mot: "Normalisation progressive", cat: "Altération de la réalité et de la responsabilité", analyse: "HIST",
    crit: "Un historique montre que des comportements auparavant perçus comme inacceptables sont devenus progressivement ordinaires, sans décision explicite de les accepter.",
    pas: "S’habituer à une contrainte normale ou adapter ses attentes n’est pas en soi une normalisation abusive.",
    question: "Qu’est-ce que tu aurais considéré comme inacceptable au début et qui te paraît aujourd’hui presque normal ?",
    verif: "Évolution dans le temps ; seuil initial ; événements successifs ; justification actuelle ; comparaison avec le début." },
  { mot: "Poubelle psychique", cat: "Altération de la réalité et de la responsabilité", analyse: "HIST",
    crit: "Les échecs, erreurs ou tensions sont attribués de manière récurrente à la même personne tandis que les réussites ou responsabilités positives restent du côté de l’autre.",
    pas: "Être responsable d’une erreur précise n’est pas une attribution systématique des torts.",
    question: "Dans les situations où quelque chose va mal, l’autre reconnaît-il parfois sa part ou la responsabilité finit-elle presque toujours par retomber sur toi ?",
    verif: "Plusieurs épisodes ; répartition des responsabilités ; reconnaissance des propres erreurs ; asymétrie succès/échecs." },
  { mot: "Projection", cat: "Altération de la réalité et de la responsabilité", analyse: "HIST",
    crit: "Le reproche adressé à l’autre correspond de façon répétée à un comportement objectivement attribuable à l’auteur, avec inversion des rôles.",
    pas: "Une accusation similaire à un comportement de l’auteur ne permet pas à elle seule de conclure à une projection psychologique.",
    question: "As-tu des exemples concrets où le comportement qu’on te reproche est aussi — ou surtout — celui de l’autre, indépendamment de ce qu’il ou elle pense intérieurement ?",
    verif: "Comportement reproché ; comportements observables des deux côtés ; répétition ; chronologie." },
  { mot: "Renversement de responsabilité", cat: "Altération de la réalité et de la responsabilité", analyse: "OUI",
    crit: "L’auteur présente son propre acte ou émotion comme causé par l’autre : « tu m’as obligé », « si je crie c’est à cause de toi », supprimant sa responsabilité sur sa réaction.",
    pas: "Reconnaître qu’un comportement de l’autre a déclenché une émotion n’est pas la même chose que nier sa responsabilité sur ses actes.",
    question: "La personne distingue-t-elle ce qui l’a déclenchée de ce qu’elle a choisi de faire ensuite, ou te rend-elle responsable de son propre comportement ?",
    verif: "Lien causal formulé ; reconnaissance de responsabilité ; choix comportemental ; demande implicite de réparation." },
  { mot: "Réécriture du passé", cat: "Altération de la réalité et de la responsabilité", analyse: "PRUDENT",
    crit: "Des accords ou événements passés sont reformulés d’une manière incompatible avec des traces, souvenirs partagés ou versions antérieures, et cette nouvelle version sert le conflit actuel.",
    pas: "Deux personnes peuvent se souvenir différemment sans réécrire volontairement le passé.",
    question: "Existe-t-il des messages, dates ou accords écrits qui permettent de comparer la version actuelle à ce qui avait été dit à l’époque ?",
    verif: "Traces disponibles ; versions antérieures ; stabilité des souvenirs ; enjeu actuel." },
  { mot: "Savoir mieux que toi", cat: "Altération de la réalité et de la responsabilité", analyse: "OUI",
    crit: "Le message affirme savoir ce que l’autre pense, ressent ou veut malgré son démenti, et traite cette interprétation comme plus vraie que son autodéfinition.",
    pas: "Faire une hypothèse sur l’état de quelqu’un ou dire « tu as l’air triste » n’est pas nécessairement nier son autodéfinition.",
    question: "Quand tu dis « non, ce n’est pas ce que je ressens », est-ce que ta réponse est acceptée ou immédiatement disqualifiée ?",
    verif: "Formulation comme hypothèse ou certitude ; place laissée à la correction ; répétition ; conséquences du désaccord." },

  // ---- Dévalorisation et atteinte à l'identité ----
  { mot: "Attaque par surprise", cat: "Dévalorisation et atteinte à l'identité", analyse: "HIST",
    crit: "Des reproches ou attaques surviennent de façon récurrente à des moments où la personne est particulièrement détendue, fatiguée, captive ou socialement exposée, ce qui augmente leur impact.",
    pas: "Un sujet difficile abordé à un mauvais moment une fois ne suffit pas.",
    question: "Est-ce que les sujets les plus agressifs arrivent souvent à des moments où tu es particulièrement fatigué·e, surpris·e ou peu libre de partir ?",
    verif: "Timing de plusieurs épisodes ; alternatives possibles ; fatigue/exposition ; réaction aux demandes de reporter." },
  { mot: "Déni de l'autre", cat: "Dévalorisation et atteinte à l'identité", analyse: "HIST",
    crit: "Les demandes, paroles ou besoins de la personne sont de façon répétée ignorés comme s’ils n’existaient pas, au-delà d’un simple désaccord ou d’une distraction.",
    pas: "Ne pas répondre immédiatement, être occupé ou ne pas pouvoir satisfaire un besoin n’est pas du déni de l’autre.",
    question: "Quand tu exprimes quelque chose d’important, obtiens-tu au moins une reconnaissance de ce que tu as dit, même si l’autre n’est pas d’accord ?",
    verif: "Fréquence ; contexte ; capacité de répondre ; reconnaissance verbale ; domaines concernés." },
  { mot: "Dévalorisation", cat: "Dévalorisation et atteinte à l'identité", analyse: "OUI",
    crit: "Le message rabaisse les capacités, la valeur, l’intelligence, le corps ou la légitimité de la personne au lieu de critiquer un comportement précis.",
    pas: "Un retour négatif précis sur une action n’est pas une dévalorisation de la personne.",
    question: "Le message critique-t-il quelque chose que tu as fait, ou te présente-t-il globalement comme incapable, inférieur·e ou sans valeur ?",
    verif: "Cible du reproche ; généralisation ; répétition ; lien avec demande/contrôle." },
  { mot: "Humiliation", cat: "Dévalorisation et atteinte à l'identité", analyse: "OUI",
    crit: "Le message cherche ou produit un rabaissement de dignité, notamment par exposition, ridicule, dégradation ou atteinte publique/intime marquée.",
    pas: "Une remarque embarrassante ou maladroite n’est pas nécessairement une humiliation intentionnelle.",
    question: "Quand tu montres que tu es mal à l’aise ou blessé·e, la personne arrête-t-elle et répare-t-elle, ou continue-t-elle à te rabaisser ?",
    verif: "Contexte public/privé ; contenu ; réaction à l’inconfort ; répétition ; information sensible." },
  { mot: "Maladresse volontaire", cat: "Dévalorisation et atteinte à l'identité", analyse: "HIST",
    crit: "Un geste présenté comme accidentel touche de façon répétée des vulnérabilités très spécifiques de la personne, surtout après qu’elles ont été connues ou signalées.",
    pas: "Une maladresse isolée, même douloureuse, ne suffit pas à établir une volonté.",
    question: "Est-ce arrivé plusieurs fois sur des choses dont la personne savait précisément qu’elles étaient importantes ou sensibles pour toi ?",
    verif: "Historique ; connaissance de la vulnérabilité ; répétition ; probabilité d’accident ; réaction après dommage." },
  { mot: "Sarcasme / mépris", cat: "Dévalorisation et atteinte à l'identité", analyse: "OUI",
    crit: "L’ironie ou l’humour sert à rabaisser, mépriser ou attaquer, puis la critique est protégée par « c’était pour rire ».",
    pas: "Une plaisanterie partagée ou un sarcasme ponctuel entre personnes consentantes n’est pas automatiquement problématique.",
    question: "Quand tu dis que cette ironie te blesse, est-ce que la personne ajuste son comportement ou te reproche de ne pas avoir d’humour ?",
    verif: "Tonalité ; cible ; réciprocité ; réaction à la limite ; répétition." },
  { mot: "Utilisation d'un public", cat: "Dévalorisation et atteinte à l'identité", analyse: "PRUDENT",
    crit: "La présence d’autres personnes est utilisée pour renforcer un reproche, révéler une information, obtenir une conformité ou rendre la défense plus coûteuse.",
    pas: "Parler d’un problème devant d’autres n’est pas toujours une utilisation d’un public, notamment si le contexte est collectif ou sécurisé.",
    question: "Est-ce que ce sujet devait réellement être abordé devant ces personnes, ou leur présence a-t-elle surtout augmenté ta honte ou réduit ta possibilité de répondre ?",
    verif: "Choix du lieu/public ; pertinence des témoins ; information privée ; possibilité de répondre." },
  { mot: "Écoute aversive", cat: "Dévalorisation et atteinte à l'identité", analyse: "HIST",
    crit: "Pendant des sujets importants, la personne manifeste de façon répétée une non-attention ostensible qui empêche l’échange : téléphone, soupirs, réponses hors sujet, départ mental.",
    pas: "Être distrait, fatigué ou occupé ponctuellement n’est pas une écoute aversive.",
    question: "Lorsque tu demandes un vrai moment d’écoute ou proposes de reporter, la personne accepte-t-elle un cadre où elle peut réellement t’écouter ?",
    verif: "Fréquence ; sujets concernés ; demandes d’attention ; possibilité de reporter ; comportement non verbal." },
  { mot: "Étiquetage", cat: "Dévalorisation et atteinte à l'identité", analyse: "OUI",
    crit: "Le message définit la personne par un trait global négatif — menteur, folle, égoïste, incapable — au lieu de décrire un comportement vérifiable.",
    pas: "Employer un adjectif dans une dispute ne suffit pas à établir une stratégie d’étiquetage durable.",
    question: "Est-ce une insulte ponctuelle, ou cette même étiquette revient-elle régulièrement pour expliquer presque tout ce que tu fais ?",
    verif: "Fréquence ; stabilité de l’étiquette ; domaines où elle est réutilisée ; effet sur l’autodéfinition." },

  // ---- Pouvoir, domination et emprise ----
  { mot: "Abus de pouvoir", cat: "Pouvoir, domination et emprise", analyse: "OUI",
    crit: "Une position hiérarchique, parentale, financière ou statutaire est utilisée au-delà de sa légitimité pour imposer des choix privés ou empêcher le refus.",
    pas: "Exercer une autorité réelle dans son champ de responsabilité n’est pas automatiquement un abus.",
    question: "Cette personne a-t-elle réellement autorité sur cette décision précise, ou utilise-t-elle son statut pour contrôler un domaine qui ne lui appartient pas ?",
    verif: "Nature du pouvoir ; domaine légitime ; demande exacte ; possibilité de recours/refus ; conséquences." },
  { mot: "Climat incestuel", cat: "Pouvoir, domination et emprise", analyse: "NON",
    crit: "Des paroles, regards ou attitudes sexualisent de façon répétée la relation adulte-enfant/adolescent et brouillent les frontières générationnelles.",
    pas: "Une discussion d’éducation sexuelle adaptée ou un compliment non sexualisé sur l’apparence ne suffit pas.",
    question: "Quels propos ou comportements précis te font parler de sexualisation, et est-ce que cela se répète au-delà d’un échange éducatif normal ?",
    verif: "Âges/rôles ; contenu exact ; fréquence ; contexte ; réaction de l’enfant ; présence de secrets ou malaise." },
  { mot: "Contrôle / Intrusion", cat: "Pouvoir, domination et emprise", analyse: "OUI",
    crit: "Le message exige un accès ou un contrôle sur téléphone, espace privé, déplacements, affaires, conversations ou décisions personnelles sans consentement libre.",
    pas: "Une demande ponctuelle d’information ou un accord de partage réciproque n’est pas automatiquement intrusif.",
    question: "Peux-tu dire non à cette demande d’accès ou de contrôle sans devoir te justifier ni subir de conséquence ?",
    verif: "Objet de l’accès ; consentement ; réciprocité ; possibilité de refuser ; sanction." },
  { mot: "Contrôle coercitif", cat: "Pouvoir, domination et emprise", analyse: "HIST",
    crit: "Un ensemble répété de surveillance, règles, isolement, contrôle économique, intimidation ou sanctions réduit concrètement la liberté quotidienne de la personne.",
    pas: "Un comportement contrôlant isolé ne suffit pas à conclure à un contrôle coercitif global.",
    question: "Dans combien de domaines de ta vie dois-tu aujourd’hui anticiper ses règles ou ses réactions pour éviter des conséquences ?",
    verif: "Plusieurs domaines de vie ; durée ; sanctions ; peur ; perte d’autonomie ; adaptation des comportements." },
  { mot: "Droits spéciaux", cat: "Pouvoir, domination et emprise", analyse: "OUI",
    crit: "Le message revendique une exemption des règles ou un traitement supérieur comme un dû, tout en exigeant que les autres respectent les contraintes communes.",
    pas: "Demander un aménagement légitime ou faire valoir un droit spécifique n’est pas un sentiment de droits spéciaux.",
    question: "Quelle règle devrait s’appliquer aux deux, et pourquoi la personne estime-t-elle qu’elle ne devrait pas s’appliquer à elle ?",
    verif: "Règle commune ; exception demandée ; justification ; symétrie ; réaction au refus." },
  { mot: "Imposture", cat: "Pouvoir, domination et emprise", analyse: "HIST",
    crit: "Le récit montre des affirmations répétées et vérifiables sur statut, réussite, rôle ou relations qui s’avèrent gonflées ou appropriées à d’autres pour soutenir une image de prestige.",
    pas: "Se présenter sous son meilleur jour ou simplifier son parcours n’est pas nécessairement une imposture.",
    question: "Quelles affirmations précises sur son parcours ou son rôle peux-tu comparer à des faits indépendants ?",
    verif: "Affirmations exactes ; éléments vérifiables ; importance dans la relation ; bénéfice obtenu." },
  { mot: "Pression sexuelle", cat: "Pouvoir, domination et emprise", analyse: "NON",
    crit: "Après un refus, une hésitation ou absence d’enthousiasme sexuel, la personne insiste, culpabilise, menace, boude ou conditionne l’affection afin d’obtenir un acte.",
    pas: "Exprimer un désir ou proposer une pratique sexuelle en respectant immédiatement un non n’est pas une pression sexuelle.",
    question: "Que se passe-t-il concrètement lorsque tu dis non, ralentis ou changes d’avis ?",
    verif: "Refus/hésitation ; réactions ; répétition ; chantage ; peur ; capacité de retirer son consentement." },
  { mot: "Redéfinition des rôles", cat: "Pouvoir, domination et emprise", analyse: "HIST",
    crit: "Une personne s’attribue de façon répétée le travail, les décisions ou les mérites réellement produits par l’autre et réécrit la répartition des contributions.",
    pas: "Résumer un travail collectif ou se tromper sur qui a fait quoi ne suffit pas.",
    question: "Quand tu précises qui a réellement fait quoi, la correction est-elle reconnue ou ta contribution continue-t-elle à être effacée ?",
    verif: "Tâches réalisées ; traces ; attribution publique ; répétition ; réactions à la correction." },
  { mot: "Rivalité avec l'enfant", cat: "Pouvoir, domination et emprise", analyse: "HIST",
    crit: "Un parent se compare à l’enfant, rabaisse ses réussites ou concurrence son apparence, ses relations ou ses succès de manière répétée.",
    pas: "Un désaccord parent-enfant ou une remarque critique ne suffit pas à établir une rivalité.",
    question: "Comment le parent réagit-il quand l’enfant réussit ou reçoit de l’attention positive : soutien, indifférence ou besoin de le rabaisser/se comparer ?",
    verif: "Nature des comparaisons ; fréquence ; moments de réussite ; réaction aux compliments adressés à l’enfant." },
  { mot: "Sabotage", cat: "Pouvoir, domination et emprise", analyse: "HIST",
    crit: "L’auteur donne son accord à un projet puis crée de façon répétée des obstacles, oublis ou retards prévisibles qui empêchent sa réalisation, avant d’en attribuer l’échec à l’autre.",
    pas: "Un retard, un oubli ou un changement d’avis ne suffit pas à conclure au sabotage.",
    question: "Sur plusieurs projets comparables, est-ce que l’accord verbal est suivi d’actes cohérents ou d’obstacles qui apparaissent systématiquement au dernier moment ?",
    verif: "Accord initial ; obstacles ; prévisibilité ; alternatives ; attribution de la faute ; répétition." },
  { mot: "Séduction narcissique", cat: "Pouvoir, domination et emprise", analyse: "HIST",
    crit: "Une phase d’idéalisation intense est suivie dans le temps d’une dévalorisation marquée, et l’espoir de retrouver la phase initiale joue un rôle dans le maintien du lien.",
    pas: "Une relation peut évoluer de l’idéalisation du début vers une vision plus réaliste sans être abusive.",
    question: "Qu’est-ce qui a concrètement changé entre la phase où tu étais idéalisé·e et la période suivante : moins d’intensité normale ou véritable dévalorisation ?",
    verif: "Chronologie ; intensité initiale ; type de retournement ; répétition ; rôle de l’espoir." },
  { mot: "Vol du territoire", cat: "Pouvoir, domination et emprise", analyse: "HIST",
    crit: "L’auteur s’approprie de façon répétée l’espace, les objets, relations, idées ou réussites de l’autre au point de réduire son sentiment de propriété et d’autonomie.",
    pas: "Partager des espaces, amis ou idées dans une relation n’est pas automatiquement une appropriation.",
    question: "Peux-tu garder des choses, espaces ou relations comme réellement tiens sans que l’autre se les approprie ou te demande de les partager ?",
    verif: "Objets/espaces concernés ; accord ; attribution ; refus ; répétition." },

  // ---- Techniques d'influence et d'engagement ----
  { mot: "Amorçage", cat: "Techniques d'influence et d'engagement", analyse: "HIST",
    crit: "Un accord est obtenu sur des conditions attractives, puis une fois l’engagement pris des conditions moins favorables sont ajoutées ou modifiées.",
    pas: "Renégocier un accord lorsque des circonstances changent n’est pas automatiquement de l’amorçage.",
    question: "Si les conditions finales avaient été annoncées dès le début, penses-tu que tu aurais accepté de la même façon ?",
    verif: "Conditions initiales ; changement ; moment du changement ; justification ; possibilité de retirer son accord." },
  { mot: "Autorité", cat: "Techniques d'influence et d'engagement", analyse: "OUI",
    crit: "Le message invoque un statut, une expertise ou une position d’autorité pour obtenir l’obéissance sans permettre de vérifier la pertinence ou de discuter la décision.",
    pas: "Une expertise réelle et pertinente peut légitimement peser dans une décision.",
    question: "Cette autorité est-elle compétente sur la décision précise dont il est question, et peut-on vérifier son raisonnement indépendamment de son statut ?",
    verif: "Autorité réelle ; domaine de compétence ; arguments fournis ; possibilité de vérification/refus." },
  { mot: "Fausse urgence", cat: "Techniques d'influence et d'engagement", analyse: "OUI",
    crit: "Le message impose une échéance immédiate ou très courte sans justification objective afin de réduire le temps de réflexion ou de consultation.",
    pas: "Une vraie échéance ou urgence ne constitue pas une fausse urgence.",
    question: "Quelle est l’échéance objective, qui l’impose, et que se passerait-il réellement si tu prenais davantage de temps ?",
    verif: "Échéance réelle ; source ; possibilité de vérifier ; coût de prendre du temps ; répétition." },
  { mot: "Influence informationnelle", cat: "Techniques d'influence et d'engagement", analyse: "HIST",
    crit: "Des informations pertinentes sont sélectionnées, omises ou cadrées de façon répétée pour orienter la décision de l’autre tout en conservant une apparence de vérité littérale.",
    pas: "Ne pas tout dire n’est pas toujours manipulatoire : chacun a droit à une vie privée et une communication peut être résumée.",
    question: "Quelle information manquante aurait changé ta décision si tu l’avais connue au moment où tu as accepté ?",
    verif: "Information omise ; devoir ou pertinence de transmission ; impact sur la décision ; répétition." },
  { mot: "Ingénierie sociale", cat: "Techniques d'influence et d'engagement", analyse: "NON",
    crit: "Une demande d’information sensible ou d’action exploite explicitement urgence, confiance, autorité ou peur pour contourner la vérification normale.",
    pas: "Une demande urgente légitime d’un proche ou professionnel connu n’est pas automatiquement de l’ingénierie sociale.",
    question: "Peux-tu vérifier indépendamment l’identité de la personne et la nécessité réelle de l’information ou de l’action demandée ?",
    verif: "Identité du demandeur ; canal ; information demandée ; possibilité de vérifier ; pression temporelle." },
  { mot: "Manipulation algorithmique", cat: "Techniques d'influence et d'engagement", analyse: "NON",
    crit: "La personne décrit une exposition répétée à des recommandations personnalisées qui réduisent la diversité des contenus vus et renforcent une représentation particulière.",
    pas: "Voir plusieurs contenus similaires dans un fil ne permet pas de conclure à une manipulation algorithmique ciblée.",
    question: "Est-ce l’algorithme lui-même que tu veux comprendre, ou quelqu’un dans ta relation utilise-t-il ces contenus pour te faire pression ?",
    verif: "Plateforme ; historique d’interactions ; diversité des sources ; mécanisme de recommandation connu." },
  { mot: "Manipulation médiatique", cat: "Techniques d'influence et d'engagement", analyse: "NON",
    crit: "Un message ou récit porte sur une campagne coordonnée, répétitive ou sélective à grande échelle qui façonne l’interprétation d’un sujet au-delà d’une relation interpersonnelle.",
    pas: "Un article biaisé ou un média avec une ligne éditoriale ne suffit pas à établir une manipulation médiatique.",
    question: "En quoi cette influence médiatique intervient-elle concrètement dans ta relation ou ta décision personnelle ?",
    verif: "Sources multiples ; répétition ; sélection des faits ; contexte médiatique." },
  { mot: "Nudges", cat: "Techniques d'influence et d'engagement", analyse: "NON",
    crit: "L’architecture de choix rend une option plus facile, visible ou par défaut tout en laissant formellement les autres possibles.",
    pas: "Toute interface bien conçue ou toute option par défaut n’est pas manipulatoire.",
    question: "Est-ce que tu peux choisir une autre option facilement et en connaissance de cause, ou la présentation rend-elle artificiellement l’autre choix difficile ?",
    verif: "Options disponibles ; défaut ; coût de sortie ; transparence ; objectif." },
  { mot: "Pied dans la porte", cat: "Techniques d'influence et d'engagement", analyse: "HIST",
    crit: "Une première petite demande acceptée est suivie d’une demande plus importante, et l’accord initial est utilisé pour favoriser la cohérence avec la seconde.",
    pas: "Deux demandes successives ne suffisent pas à établir un pied-dans-la-porte.",
    question: "Quelle petite demande a été acceptée d’abord, et comment ce premier oui a-t-il été utilisé lorsque la demande suivante est arrivée ?",
    verif: "Chronologie ; taille des demandes ; lien entre elles ; invocation du premier oui ; possibilité de refuser la seconde." },
  { mot: "Porte-au-nez", cat: "Techniques d'influence et d'engagement", analyse: "HIST",
    crit: "Une demande initiale manifestement excessive est refusée, puis une demande plus petite est présentée immédiatement comme concession et paraît raisonnable par contraste.",
    pas: "Réduire sincèrement une demande après négociation n’est pas nécessairement une porte-au-nez.",
    question: "La première demande semblait-elle réellement souhaitée, ou surtout suffisamment excessive pour que la seconde paraisse modeste ?",
    verif: "Montant/importance des deux demandes ; timing ; faisabilité de la première ; caractère préparé du recul." },
  { mot: "Preuve sociale", cat: "Techniques d'influence et d'engagement", analyse: "OUI",
    crit: "Le message invoque « tout le monde », la majorité, les proches ou un groupe pour faire douter la personne de son propre jugement ou obtenir sa conformité.",
    pas: "Citer un consensus réel et pertinent n’est pas automatiquement une preuve sociale manipulatoire.",
    question: "Peux-tu savoir qui pense réellement cela et sur quels faits, ou « tout le monde » reste-t-il une majorité vague impossible à vérifier ?",
    verif: "Groupe invoqué ; vérifiabilité ; pertinence ; usage pour informer ou invalider." },
  { mot: "Principe de cohérence", cat: "Techniques d'influence et d'engagement", analyse: "OUI",
    crit: "Un engagement, une promesse ou une position passée est utilisé pour rendre moralement ou psychologiquement difficile toute révision de la décision actuelle.",
    pas: "Rappeler un accord existant est souvent normal et nécessaire.",
    question: "La personne accepte-t-elle qu’un accord puisse être renégocié si les circonstances ou ton consentement changent ?",
    verif: "Nature de l’accord ; changement de circonstances ; droit de renégocier ; culpabilisation liée au changement." },
  { mot: "Rareté / peur de perdre", cat: "Techniques d'influence et d'engagement", analyse: "OUI",
    crit: "La perte d’une relation, opportunité ou ressource est présentée comme imminente et irréversible pour provoquer une décision précipitée.",
    pas: "Une opportunité réellement limitée ou une conséquence irréversible peut être factuelle.",
    question: "Ce qui est présenté comme « dernière chance » est-il réellement limité par une contrainte externe, ou uniquement par la décision de l’autre ?",
    verif: "Caractère réel de la rareté ; échéance ; contrôle de l’auteur ; possibilité de vérifier." },
  { mot: "Réciprocité", cat: "Techniques d'influence et d'engagement", analyse: "OUI",
    crit: "Une faveur ou ressource reçue crée une obligation implicite de rendre, même lorsque la contrepartie n’avait pas été convenue.",
    pas: "La réciprocité est une norme sociale normale et peut soutenir des échanges équilibrés.",
    question: "Est-ce une réciprocité librement négociée, ou te sens-tu obligé·e de rendre quelque chose que tu n’avais jamais accepté de devoir ?",
    verif: "Faveur ; attente de retour ; consentement ; proportion ; liberté de refuser." },
  { mot: "Surcharge / urgence", cat: "Techniques d'influence et d'engagement", analyse: "OUI",
    crit: "Le message combine urgence, volume d’informations, demandes multiples ou pression temporelle de manière à réduire la capacité de réflexion avant réponse.",
    pas: "Une situation complexe ou réellement urgente peut légitimement produire beaucoup d’informations en peu de temps.",
    question: "Quand tu demandes du temps pour réfléchir ou traiter les sujets un par un, est-ce possible ou la pression augmente-t-elle ?",
    verif: "Nombre de demandes ; délai ; possibilité de différer ; vraie urgence ; conséquences de demander du temps." },
  { mot: "Sympathie", cat: "Techniques d'influence et d'engagement", analyse: "PRUDENT",
    crit: "La sympathie, la ressemblance, le charme ou les compliments augmentent l’acceptation d’une demande, et l’analyse porte sur ce levier d’influence plutôt que sur une manipulation certaine.",
    pas: "Apprécier quelqu’un et être plus enclin à l’aider est normal ; ce principe ne doit pas être étiqueté comme toxique en soi.",
    question: "Est-ce que tu aurais accepté la même demande venant de quelqu’un que tu apprécies moins ou avec qui tu te sens moins proche ?",
    verif: "Nature du lien ; demande ; rôle des compliments/ressemblances ; liberté de refuser ; répétition." },
  { mot: "Unité / appartenance", cat: "Techniques d'influence et d'engagement", analyse: "OUI",
    crit: "L’appartenance commune — famille, couple, équipe, communauté — est invoquée pour obtenir loyauté, secret, conformité ou renoncement à un désaccord.",
    pas: "Faire appel au collectif ou à l’entraide n’est pas automatiquement problématique.",
    question: "Le « nous » sert-il à coopérer, ou à rendre un refus, une critique ou une demande d’aide extérieure déloyale ?",
    verif: "Groupe invoqué ; comportement demandé ; possibilité de désaccord ; secret/loyauté exigés ; sanctions." },

  // ---- Mécanismes d'attachement et de maintien dans la relation ----
  { mot: "Cycle de la violence", cat: "Mécanismes d'attachement et de maintien dans la relation", analyse: "NON",
    crit: "Le récit montre éventuellement une répétition de phases de tension, épisode violent, justification/apaisement et reprise, mais ce modèle est utilisé comme grille possible, jamais comme séquence obligatoire.",
    pas: "Une relation violente ne suit pas nécessairement ce cycle, et un conflit suivi d’excuses ne suffit pas.",
    question: "Est-ce que tu observes réellement une séquence qui revient, ou les épisodes ne suivent-ils pas ce schéma ?",
    verif: "Chronologie de plusieurs épisodes ; nature des violences ; phases d’apaisement ; changements réels ou promesses." },
  { mot: "Dissonance cognitive", cat: "Mécanismes d'attachement et de maintien dans la relation", analyse: "NON",
    crit: "La personne décrit simultanément deux croyances, valeurs ou constats incompatibles qui créent un inconfort et l’amènent à minimiser, justifier ou réinterpréter l’un des deux.",
    pas: "Avoir des sentiments contradictoires ou changer d’avis n’est pas automatiquement une dissonance cognitive problématique.",
    question: "Quelles sont les deux choses que tu crois vraies en même temps et qui te semblent difficiles à faire tenir ensemble ?",
    verif: "Croyances en tension ; comportements ; justifications ; décisions évitées ; évolution." },
  { mot: "Dépendance affective", cat: "Mécanismes d'attachement et de maintien dans la relation", analyse: "NON",
    crit: "La personne décrit une peur marquée de perdre le lien, un besoin de validation ou une difficulté à agir sans l’autre, avec retentissement réel sur son autonomie.",
    pas: "Être très attaché, dépendre temporairement d’un proche ou craindre une rupture ne suffit pas à qualifier une dépendance affective.",
    question: "Qu’est-ce que tu n’oses plus faire ou décider seul·e parce que tu crains de perdre cette relation ?",
    verif: "Durée ; autonomie décisionnelle ; peur de l’abandon ; renoncements ; fonctionnement dans d’autres relations." },
  { mot: "Emprise", cat: "Mécanismes d'attachement et de maintien dans la relation", analyse: "NON",
    crit: "Le récit montre une réduction progressive et globale de la liberté de penser, décider ou agir, liée à plusieurs mécanismes de contrôle, peur, isolement ou dépendance.",
    pas: "Un conflit, une relation déséquilibrée ou un seul comportement contrôlant ne suffit pas à établir une emprise.",
    question: "Dans quels domaines de ta vie sens-tu que ta liberté de penser ou d’agir s’est réduite depuis cette relation ?",
    verif: "Durée ; domaines touchés ; autonomie avant/après ; peur ; isolement ; contrôle ; capacité à dire non." },
  { mot: "Identification à l'agresseur", cat: "Mécanismes d'attachement et de maintien dans la relation", analyse: "NON",
    crit: "La personne reprend durablement les justifications, valeurs ou accusations de l’auteur contre elle-même, jusqu’à défendre des comportements qui la blessent ou se tenir pour responsable.",
    pas: "Comprendre le point de vue de l’autre ou reconnaître sa propre part n’est pas une identification à l’agresseur.",
    question: "Quand tu reprends ses explications, est-ce que cela t’aide à comprendre la situation ou cela finit-il surtout par rendre tes propres limites illégitimes ?",
    verif: "Formulations auto-accusatrices ; justifications de l’autre ; évolution dans le temps ; capacité à reconnaître ses propres besoins." },
  { mot: "Lien traumatique", cat: "Mécanismes d'attachement et de maintien dans la relation", analyse: "NON",
    crit: "Un attachement intense persiste dans un contexte de violence ou contrôle avec alternance de mauvais traitements et de réconfort, et la séparation reste très difficile malgré la reconnaissance du danger.",
    pas: "Un attachement fort à une personne qui a fait souffrir ne suffit pas à établir un lien traumatique.",
    question: "Qu’est-ce qui se passe juste après les épisodes les plus douloureux : éloignement, excuses, grande tendresse, promesses ou autre chose ?",
    verif: "Violence/contrôle ; alternance ; dépendance ; peur ; difficulté de séparation ; durée." },
  { mot: "Lune de miel", cat: "Mécanismes d'attachement et de maintien dans la relation", analyse: "NON",
    crit: "Après un épisode difficile, une période marquée de calme, tendresse, excuses ou promesses réduit temporairement la tension et peut relancer l’espoir.",
    pas: "Une réconciliation sincère après un conflit n’est pas automatiquement une « lune de miel » abusive.",
    question: "Après les excuses ou la période douce, qu’est-ce qui change concrètement et combien de temps cela dure-t-il ?",
    verif: "Épisode précédent ; contenu des excuses ; actions concrètes ; durée de l’amélioration ; répétition." },
  { mot: "Rationalisation", cat: "Mécanismes d'attachement et de maintien dans la relation", analyse: "NON",
    crit: "La personne produit des explications qui rendent un comportement blessant plus acceptable et diminuent l’urgence de se protéger, malgré des faits répétés.",
    pas: "Chercher le contexte et comprendre les difficultés de l’autre n’est pas en soi une rationalisation.",
    question: "Cette explication t’aide-t-elle à comprendre sans excuser, ou te conduit-elle à accepter encore quelque chose que tu juges pourtant blessant ?",
    verif: "Explication donnée ; faits qu’elle couvre ; répétition ; limites maintenues ou abandonnées ; alternatives." },
  { mot: "Renforcement intermittent", cat: "Mécanismes d'attachement et de maintien dans la relation", analyse: "NON",
    crit: "Un historique montre que l’attention, la tendresse ou les récompenses relationnelles apparaissent de manière imprévisible après des périodes difficiles, ce qui entretient fortement l’attente et la persistance.",
    pas: "Des variations d’affection normales ne suffisent pas, et l’IA ne doit pas affirmer que ce schéma est volontairement organisé.",
    question: "Est-ce que les bons moments arrivent de façon suffisamment imprévisible pour que tu te retrouves à attendre constamment leur retour ?",
    verif: "Imprévisibilité ; alternance ; effet sur l’espoir ; durée ; association avec comportements nocifs." },
  { mot: "Triangle de Karpman", cat: "Mécanismes d'attachement et de maintien dans la relation", analyse: "NON",
    crit: "Le récit peut être éclairé par des passages entre positions de victime, persécuteur et sauveur, mais cette grille sert à observer des rôles interactionnels temporaires, pas à définir les personnes.",
    pas: "Un conflit où quelqu’un se plaint, aide ou attaque ne suffit pas à valider le triangle de Karpman.",
    question: "Est-ce que cette grille t’aide à comprendre un changement de rôles concret dans la dispute, ou risque-t-elle surtout de mettre artificiellement les deux côtés sur le même plan ?",
    verif: "Séquence précise ; changements de rôle ; fonction de chaque position ; présence éventuelle de violence/coercition." },

  // ---- Effets psychologiques et cognitifs ----
  { mot: "Charge mentale", cat: "Effets psychologiques et cognitifs", analyse: "NON",
    crit: "La personne décrit une responsabilité cognitive continue d’anticiper, planifier, se souvenir et coordonner de nombreuses tâches pour autrui, avec fatigue ou surcharge.",
    pas: "Avoir beaucoup de tâches pendant une période chargée n’est pas automatiquement une charge mentale relationnelle déséquilibrée.",
    question: "Qui doit penser à ce qu’il faut faire, vérifier que c’est fait et rappeler les choses aux autres, même lorsque les tâches sont ensuite partagées ?",
    verif: "Répartition de l’anticipation ; responsabilités invisibles ; capacité à déléguer ; durée ; impact." },
  { mot: "Dissociation", cat: "Effets psychologiques et cognitifs", analyse: "NON",
    crit: "La personne décrit déconnexion, irréalité, impression d’être spectatrice, trous ou anesthésie émotionnelle dans des situations de stress intense.",
    pas: "Être distrait, figé, fatigué ou avoir un souvenir flou ne permet pas de conclure à une dissociation.",
    question: "Quand tu dis que tu te sens « ailleurs » ou déconnecté·e, est-ce plutôt une impression d’irréalité, une perte de souvenirs, une anesthésie émotionnelle ou autre chose ?",
    verif: "Description précise ; fréquence ; contexte de stress ; durée ; impact fonctionnel ; autres causes possibles." },
  { mot: "Hypervigilance", cat: "Effets psychologiques et cognitifs", analyse: "NON",
    crit: "La personne décrit une surveillance permanente des signes de danger, du ton, des horaires ou de l’humeur de l’autre, avec tension et difficulté à se relâcher.",
    pas: "Être attentif après une dispute ou prudent dans une période instable n’est pas forcément de l’hypervigilance.",
    question: "Même quand rien ne se passe, te surprends-tu à surveiller en permanence des signes annonçant sa prochaine réaction ?",
    verif: "Durée ; déclencheurs ; capacité à se détendre ; sommeil ; comportements d’anticipation ; contexte de danger." },
  { mot: "Perte d'estime de soi", cat: "Effets psychologiques et cognitifs", analyse: "NON",
    crit: "La personne décrit une dégradation durable de sa perception de sa valeur, de ses compétences ou de sa légitimité, en lien avec des critiques ou invalidations répétées.",
    pas: "Douter de soi après un échec ou une dispute n’est pas forcément une perte d’estime de soi installée.",
    question: "Qu’est-ce que tu pensais de tes capacités ou de ta valeur avant cette période, et qu’est-ce qui a changé aujourd’hui ?",
    verif: "Avant/après relation ; domaines touchés ; fréquence des auto-dévalorisations ; impact sur décisions ; critiques reçues." },
  { mot: "Sentiment d'impuissance", cat: "Effets psychologiques et cognitifs", analyse: "NON",
    crit: "Après des tentatives répétées perçues comme inefficaces, la personne cesse d’essayer ou pense qu’aucune action n’a d’effet, même lorsqu’il existe encore des options.",
    pas: "Décider rationnellement qu’une stratégie ne fonctionne pas n’est pas un sentiment d’impuissance généralisé.",
    question: "Quand tu dis « ça ne sert à rien », parles-tu d’une stratégie précise ou as-tu l’impression que plus aucune action de ta part ne peut changer quoi que ce soit ?",
    verif: "Tentatives passées ; résultats ; domaines généralisés ; options non essayées ; peur/coût d’agir." },
  { mot: "Sidération", cat: "Effets psychologiques et cognitifs", analyse: "NON",
    crit: "La personne décrit une incapacité immédiate à parler, agir ou fuir pendant un choc ou une scène menaçante, avec sensation de blocage involontaire.",
    pas: "Ne pas savoir quoi répondre, hésiter ou choisir de rester silencieux n’est pas nécessairement une sidération.",
    question: "Sur le moment, avais-tu le sentiment de choisir de ne pas réagir, ou d’être physiquement/mentalement incapable de faire quoi que ce soit ?",
    verif: "Contexte ; perception du danger ; sensations corporelles ; durée ; retour à l’action ; fréquence." },
  { mot: "Vulnérabilité biocomportementale", cat: "Effets psychologiques et cognitifs", analyse: "NON",
    crit: "La personne se trouvait dans un état de fatigue, faim, stress ou manque de sommeil susceptible de réduire ses ressources de décision au moment d’une pression.",
    pas: "Être fatigué ne signifie pas être manipulable ni invalider une décision.",
    question: "Dans quel état physique ou émotionnel étais-tu au moment de décider, et pouvais-tu raisonnablement remettre la décision à plus tard ?",
    verif: "État physique ; timing de la demande ; possibilité de reporter ; importance de la décision ; exploitation éventuelle." },

  // ---- Biais cognitifs favorisant la prise ou le maintien ----
  { mot: "Ancrage", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "Une première impression, promesse ou référence initiale continue de peser disproportionnellement sur le jugement actuel malgré des informations plus récentes.",
    pas: "Se souvenir du début d’une relation ou tenir compte d’un prix de référence n’est pas automatiquement un biais problématique.",
    question: "Si tu mettais de côté le tout début de la relation, comment évaluerais-tu uniquement ce qui se passe depuis plusieurs mois ?",
    verif: "Ancre initiale ; données actuelles ; poids accordé aux deux ; décisions prises." },
  { mot: "Aversion à la perte", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "La peur de perdre ce qui existe pèse plus lourd dans la décision que les bénéfices possibles d’un changement équivalent ou supérieur.",
    pas: "Être prudent face à une perte réelle et importante n’est pas un biais irrationnel.",
    question: "Si tu imaginais ne rien « perdre » symboliquement en changeant, quelle option te semblerait la plus favorable aujourd’hui ?",
    verif: "Ce qui pourrait être perdu ; bénéfices attendus ; probabilités ; alternatives ; importance réelle." },
  { mot: "Biais d'optimisme", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "La personne surestime la probabilité d’une amélioration future malgré un historique stable ou répété qui fournit peu d’indices de changement.",
    pas: "Espérer une amélioration n’est pas forcément un biais, surtout s’il existe des actions concrètes et durables.",
    question: "Sur quoi repose ton espoir aujourd’hui : des actes nouveaux et durables, ou surtout la possibilité que les choses finissent par changer ?",
    verif: "Historique ; actions concrètes ; durée du changement ; promesses ; rechutes." },
  { mot: "Biais de confirmation", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "La personne sélectionne surtout les épisodes qui confirment une croyance préalable et minimise systématiquement les informations qui la contredisent.",
    pas: "Chercher des exemples qui confirment une hypothèse est normal ; le biais suppose une asymétrie dans le traitement des contre-exemples.",
    question: "Quels faits iraient contre l’idée que tu te fais de cette relation, et quelle place leur donnes-tu quand tu les regardes ensemble ?",
    verif: "Croyance initiale ; éléments pour/contre ; poids accordé ; réaction aux contradictions." },
  { mot: "Biais du statu quo", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "La situation actuelle est maintenue principalement parce qu’elle est familière, alors qu’un changement est évité en raison de l’incertitude plus que de ses coûts objectifs.",
    pas: "Choisir de rester parce que l’option actuelle est réellement meilleure ou moins risquée n’est pas un biais du statu quo.",
    question: "Si les deux options t’étaient présentées aujourd’hui comme nouvelles, laquelle choisirais-tu en tenant compte aussi de ta sécurité réelle ?",
    verif: "Options ; risques objectifs ; familiarité ; coûts du changement ; sécurité." },
  { mot: "Cadrage", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "La même situation est présentée sous un angle particulier — amour, protection, loyauté, perte — qui modifie la décision sans changer les faits sous-jacents.",
    pas: "Toute formulation possède un cadre ; le cadrage n’est pas automatiquement manipulateur.",
    question: "Si on reformule exactement les mêmes faits avec des mots neutres, est-ce que la décision te paraît toujours aussi évidente ?",
    verif: "Faits invariants ; formulations alternatives ; décision produite ; éléments omis." },
  { mot: "Conformisme", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "La personne s’aligne sur le groupe ou tait son désaccord principalement parce qu’elle se sent seule face à une majorité réelle ou supposée.",
    pas: "Être convaincu par plusieurs personnes ou suivre une norme raisonnable n’est pas nécessairement du conformisme problématique.",
    question: "Si personne autour de toi ne connaissait ton choix, penserais-tu la même chose ou te sentirais-tu plus libre de décider autrement ?",
    verif: "Groupe ; opinions réelles ; arguments ; peur du rejet ; décision personnelle initiale." },
  { mot: "Coûts irrécupérables", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "Le temps, l’argent, les efforts ou les années déjà investis deviennent une raison de poursuivre, même si ces investissements sont irrécupérables et ne changent pas les perspectives futures.",
    pas: "Tenir compte des conséquences pratiques d’un départ n’est pas un biais de coûts irrécupérables.",
    question: "Si tout ce que tu as déjà investi était impossible à récupérer dans tous les cas, qu’est-ce qui compterait le plus pour ta décision à partir d’aujourd’hui ?",
    verif: "Investissements passés ; coûts futurs ; bénéfices attendus ; obligations actuelles ; sécurité." },
  { mot: "Croyance en un monde juste", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "La personne explique ce qu’elle subit par l’idée qu’elle doit l’avoir mérité, provoqué ou attiré, parce qu’un monde juste devrait récompenser les bons comportements.",
    pas: "Reconnaître une conséquence directe de ses propres actes n’est pas une croyance en un monde juste.",
    question: "Qu’est-ce qui te fait penser que le fait d’avoir subi cela signifie nécessairement que tu l’avais mérité ou provoqué ?",
    verif: "Faits ; responsabilité objective ; auto-blâme ; logique morale ; réactions des tiers." },
  { mot: "Disponibilité", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "Le jugement global repose surtout sur un épisode récent, spectaculaire ou facilement mémorisable plutôt que sur l’ensemble des événements disponibles.",
    pas: "Se servir d’un exemple marquant n’est pas forcément un biais si cet exemple est réellement représentatif ou grave.",
    question: "Cet épisode est-il surtout le plus facile à rappeler, ou reflète-t-il réellement la fréquence et la gravité de ce qui se passe ?",
    verif: "Épisodes disponibles ; fréquence ; gravité ; récence ; représentativité." },
  { mot: "Effet de halo", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "Une qualité positive globale — charme, compétence, générosité, réputation — est utilisée implicitement pour conclure que la personne ne peut pas avoir de comportements problématiques dans un autre contexte.",
    pas: "Reconnaître les qualités de quelqu’un n’est pas un effet de halo problématique.",
    question: "Si tu mettais de côté cette grande qualité ou sa réputation, comment jugerais-tu uniquement les comportements précis qui te posent problème ?",
    verif: "Qualité dominante ; faits problématiques ; domaines ; témoignages ; poids accordé à la réputation." },
  { mot: "Erreur d'attribution", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "Un comportement est expliqué principalement par un trait de personnalité supposé alors que le contexte, les contraintes ou une dynamique d’emprise pourraient offrir d’autres explications.",
    pas: "Parfois un comportement reflète bien une disposition personnelle ; l’erreur d’attribution est une tendance, pas une interdiction d’évaluer les traits.",
    question: "Quelles contraintes ou circonstances pourraient expliquer ce comportement avant de conclure qu’il vient simplement de « qui est cette personne » ?",
    verif: "Comportement ; contexte ; contraintes ; alternatives explicatives ; répétition dans différents contextes." },
  { mot: "Habituation", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "NON",
    crit: "Des comportements auparavant perçus comme anormaux suscitent de moins en moins de réaction parce qu’ils se répètent, même si leur gravité objective n’a pas diminué.",
    pas: "S’habituer à une situation neutre ou développer de meilleures capacités d’adaptation n’est pas un problème en soi.",
    question: "Est-ce le comportement qui est devenu moins grave, ou est-ce surtout ta réaction qui s’est émoussée à force qu’il se répète ?",
    verif: "Réaction initiale ; réaction actuelle ; comportement identique ; fréquence ; gravité." },
  { mot: "Illusion de contrôle", cat: "Biais cognitifs favorisant la prise ou le maintien", analyse: "OUI",
    crit: "La personne pense qu’en modifiant suffisamment son propre comportement elle pourra contrôler ou prévenir les réactions blessantes de l’autre, malgré des tentatives répétées infructueuses.",
    pas: "Adapter sa communication peut réellement améliorer certaines relations ; toute recherche d’influence n’est pas une illusion de contrôle.",
    question: "Qu’est-ce qui dépend réellement de toi dans cette situation, et qu’est-ce qui reste le choix ou la responsabilité de l’autre même si tu fais tout « parfaitement » ?",
    verif: "Tentatives d’adaptation ; résultats ; responsabilité de l’autre ; domaines contrôlables/non contrôlables ; peur." },
];

module.exports = { FAMILLES, MECANISMES };
